server:
  downloads_address: "C:/Users/mrdor/PycharmProjects/Hunterbee/server/tempfiles/downloads"
  address: "localhost"
  port: 6060

LogAggregator:
  downloads_address: "C:/Users/mrdor/PycharmProjects/Hunterbee/server/tempfiles/downloads"
  aggregated_logs_address: "C:/Users/mrdor/PycharmProjects/Hunterbee/server/tempfiles/aggregated"

Clustering:
  filtered_logs_address: "C:/Users/mrdor/PycharmProjects/Hunterbee/server/tempfiles/filtered"

LogFilterer:
    aggregated_logs_address: "C:/Users/mrdor/PycharmProjects/Hunterbee/server/tempfiles/aggregated"
    filtered_logs_address: "C:/Users/mrdor/PycharmProjects/Hunterbee/server/tempfiles/filtered"

LogChecker:
  filtered_logs_address: "C:/Users/mrdor/PycharmProjects/Hunterbee/server/tempfiles/filtered"
  database_address: "C:/Users/mrdor/PycharmProjects/Hunterbee/server/database"